package com.zxy97.ssm.template;

import com.zxy97.ssm.config.Config;
import static com.zxy97.ssm.template.Template.write;
import static java.lang.String.format;

public class WebXmlTemplate extends Template {

    private String getContent() {

        StringBuilder result = new StringBuilder();
        result.append("<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n")
                .append("<web-app version=\"3.1\" xmlns=\"http://xmlns.jcp.org/xml/ns/javaee\" \n")
                .append("    xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" \n")
                .append("    xsi:schemaLocation=\"http://xmlns.jcp.org/xml/ns/javaee \n")
                .append("    http://xmlns.jcp.org/xml/ns/javaee/web-app_3_1.xsd\">\n\n")
                .append("    <!-- 之所以将web.xml放在这里是怕覆盖已有web.xml。\n")
                .append("         如果您未配置web.xml，将本文件放到WEB-INF目录下即可。\n")
                .append("         如果您已配置web.xml，将本文件的内容选择性地放到web.xml中即可。-->\n\n")
                .append("    <!-- 配置 springIOC -->\n")
                .append("    <listener>\n")
                .append("        <listener-class>org.springframework.web.context.ContextLoaderListener</listener-class>\n")
                .append("    </listener>\n")
                .append("    <context-param>  \n")
                .append("        <param-name>contextConfigLocation</param-name>  \n")
                .append("        <param-value>classpath:applicationContext.xml</param-value>\n")
                .append("    </context-param>\n\n")
                .append("    <!-- SpringMVC核心控制器 -->\n")
                .append("    <servlet>\n")
                .append("        <servlet-name>springmvc</servlet-name>\n")
                .append("        <servlet-class>org.springframework.web.servlet.DispatcherServlet</servlet-class>\n")
                .append("        <init-param>\n")
                .append("            <param-name>contextConfigLocation</param-name>\n")
                .append("            <param-value>classpath:springmvc-servlet.xml</param-value>\n")
                .append("        </init-param>\n")
                .append("        <!--优先级-->\n")
                .append("        <load-on-startup>1</load-on-startup>\n")
                .append("    </servlet>\n")
                .append("    <servlet-mapping>\n")
                .append("        <servlet-name>springmvc</servlet-name>\n")
                .append("        <url-pattern>/</url-pattern>\n")
                .append("    </servlet-mapping>\n\n")
                .append("    <!-- 字符编码过滤器，默认为UTF-8编码 -->\n")
                .append("    <filter>\n")
                .append("        <filter-name>characterEncodingFilter</filter-name>\n")
                .append("        <filter-class>org.springframework.web.filter.CharacterEncodingFilter</filter-class>\n")
                .append("        <init-param>\n")
                .append("            <param-name>encoding</param-name>\n")
                .append("            <param-value>UTF-8</param-value>\n")
                .append("        </init-param>\n")
                .append("    </filter>\n")
                .append("    <filter-mapping>\n")
                .append("        <filter-name>characterEncodingFilter</filter-name>\n")
                .append("        <url-pattern>/*</url-pattern>\n")
                .append("    </filter-mapping>\n\n")
                .append("    <!-- 增加 put 和 delete 的 HTTP方法 -->\n")
                .append("    <filter>\n")
                .append("        <filter-name>HiddenHttpMethodFilter</filter-name>\n")
                .append("        <filter-class>org.springframework.web.filter.HiddenHttpMethodFilter</filter-class>\n")
                .append("    </filter>\n")
                .append("    <filter-mapping>\n")
                .append("        <filter-name>HiddenHttpMethodFilter</filter-name>\n")
                .append("        <url-pattern>/*</url-pattern>\n")
                .append("    </filter-mapping>\n\n")
                .append("    <!-- 配置网站首页 -->\n")
                .append("    <welcome-file-list>\n")
                .append("        <welcome-file>redirect.jsp</welcome-file>\n")
                .append("        <welcome-file>index.html</welcome-file>\n")
                .append("    </welcome-file-list>\n\n")
                .append("    <!-- 如果超过以下时间无操作，则注销会话，单位为分钟 -->\n")
                .append("    <session-config>\n")
                .append("        <session-timeout>\n")
                .append("            60\n")
                .append("        </session-timeout>\n")
                .append("    </session-config>\n\n")
                .append("<!--\n")
                .append("    <jsp-config>\n")
                .append("        <taglib>\n")
                .append("            <taglib-uri>constants</taglib-uri>\n")
                .append("            <taglib-location>/WEB-INF/constants.tld</taglib-location>\n")
                .append("        </taglib>\n")
                .append("    </jsp-config>\n\n")
                .append("-->\n")
                .append("    <!-- 默认的错误处理页面 -->\n")
                .append("    \n")
                .append( "    <!-- 无权限 -->\n")
                .append( "    <error-page>\n")
                .append("        <error-code>403</error-code>\n")
                .append("        <location>/page/error/403.jsp</location>\n")
                .append("    </error-page>\n\n")
                .append("    <!-- 页面不存在 -->\n")
                .append("    <error-page>\n")
                .append("        <error-code>404</error-code>\n")
                .append("        <location>/page/error/404.jsp</location>\n")
                .append("    </error-page>\n")
                .append("    <!-- 仅仅在调试的时候注视掉,在正式部署的时候不能注释 -->\n")
                .append("    <!-- 这样配置也是可以的，表示发生500错误的时候，转到500.jsp页面处理。 -->\n\n")
                .append("    <!-- 服务器内容错误 -->\n")
                .append("<!--\n")
                .append("    <error-page>\n")
                .append("        <error-code>500</error-code>\n")
                .append("        <location>/page/error/500.jsp</location>\n")
                .append("    </error-page>\n")
                .append("-->\n\n")
                .append("    <!-- 这样的配置表示如果jsp页面或者servlet发生java.lang.Exception类型（当然包含子类）的异常就会转到500.jsp页面处理。 -->\n")
                .append("<!-- \n")
                .append("    <error-page> \n")
                .append("        <exception-type>java.lang.Exception</exception-type>\n")
                .append("        <location>/page/error/500.jsp</location>\n")
                .append("    </error-page>\n")
                .append("    <error-page>\n")
                .append("        <exception-type>java.lang.Throwable</exception-type>\n")
                .append("        <location>/page/error/500.jsp</location>\n")
                .append("    </error-page>\n")
                .append("-->\n")
                .append("<!-- \n")
                .append("   当error-code和exception-type都配置时，exception-type配置的页面优先级高\n")
                .append("   及出现500错误，发生异常Exception时会跳转到500.jsp\n")
                .append("-->\n\n")
                .append("</web-app>\n\n")
                .append("<!--\n" )
                .append("以下是我向大家推荐的jar包\n" )
                .append("\n" )
                .append("文件上传（可选）：\n" )
                .append("commons-fileupload-1.3.2.jar\n" )
                .append("commons-io-2.5.jar\n" )
                .append("\n" )
                .append("JSTL标签库（可选）：\n" )
                .append("jstl.jar\n" )
                .append("standard.jar\n" )
                .append("\n" )
                .append("测试框架（可选）：\n" )
                .append("junit-4.9.jar\n" )
                .append("spring-test-4.0.1.RELEASE\n" )
                .append("\n" )
                .append("邮件发送（可选）：\n" )
                .append("mail.jar\n" )
                .append("\n" )
                .append("MyBatis（必选）：\n" )
                .append("mybatis-3.2.7.jar\n" )
                .append("mysql-connector-java-5.1.8-bin.jar\n" )
                .append("\n" )
                .append("Spring).append(SpringMVC（必选）：\n" )
                .append("org-apache-commons-logging.jar\n" )
                .append("spring-aop-4.0.1.RELEASE.jar\n" )
                .append("spring-beans-4.0.1.RELEASE.jar\n" )
                .append("spring-context-4.0.1.RELEASE.jar\n" )
                .append("spring-core-4.0.1.RELEASE.jar\n" )
                .append("spring-expression-4.0.1.RELEASE.jar\n" )
                .append("spring-web-4.0.1.RELEASE.jar\n" )
                .append("spring-webmvc-4.0.1.RELEASE.jar\n" )
                .append("-->");
        return result.toString();
    }

    private String getFilePath(Config config) {
        String src = config.getSrc();
        return format("%s/web.xml", src);
    }

    @Override
    public void createFile(Config config) {
        write(getFilePath(config), getContent());
    }

}
